<div class="alert alert-danger" role="alert">
<h1 align="center"><font size = 14>Numpy Library</font></h1>
<h4 align="center">August, 20_2024<h4>
<h3 align="center">Armin Amani</h3>

<div class="alert alert-danger" role="alert">
📤 Import Libraries

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.4


<div class="alert alert-danger" role="alert">
🔎 Check the methods that are used in numpy

In [3]:
# np.array
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# np.ones
b1 = np.ones((3))
b2 = np.ones(3)

In [5]:
print(b1,"\n")
print(b2)

[1. 1. 1.] 

[1. 1. 1.]


In [6]:
b3 = np.ones((2,4))
b3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# np.zeros
c1 = np.zeros((3))
c2 = np.zeros(3)

In [8]:
print(c1,"\n")
print(c2)

[0. 0. 0.] 

[0. 0. 0.]


In [9]:
c3 = np.zeros((2,4))
c3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# np.arange
d = np.arange(20)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
# arange with step
e = np.arange(0,20,2)
e

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# np.reshape
f = d.reshape(4,5)
f

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
# ndim ,shape ,dtype ,size
print(f"shape of f is : {f.shape}")
print(f"dimension of f is : {f.ndim}")
print(f"size of f is : {f.size}")
print(f"type of f is : {f.dtype}")

shape of f is : (4, 5)
dimension of f is : 2
size of f is : 20
type of f is : int32


In [14]:
# random.rand
g = np.random.rand(5,4)
g

array([[0.96529484, 0.27246952, 0.279216  , 0.63589651],
       [0.52406778, 0.73066731, 0.88812741, 0.72070975],
       [0.46107275, 0.96234813, 0.78809381, 0.60412887],
       [0.73344892, 0.21297116, 0.20904326, 0.4377261 ],
       [0.51446008, 0.61690994, 0.61112661, 0.84718951]])

In [15]:
# random.randn
h = np.random.randn(3)
h

array([-0.61010723,  0.55283484, -0.32047204])

In [16]:
# random.randint
I = np.random.randint(10, size=(3,5))
I

array([[5, 8, 5, 6, 9],
       [6, 4, 3, 5, 0],
       [9, 8, 6, 1, 9]])

In [17]:
# np.linespace
J = np.linspace(0,20,4)
J

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [18]:
k = np.arange(40)
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [19]:
# np.append
k = np.append(k,40)
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40])

In [20]:
# np.delete
k = np.delete(k,0)
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [21]:
# np.flip
k = np.flip(k)
k

array([40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24,
       23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,
        6,  5,  4,  3,  2,  1])

In [22]:
# np.sort
k = np.sort(k)
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [23]:
# np.concatenate
l = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

m = np.array([[11,12,13],
              [14,15,16],
              [17,18,19]])

n = np.concatenate([l,m])
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [24]:
o = np.arange(40).reshape(4,2,5)
o

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [25]:
o.ndim

3

In [26]:
p = np.eye(6)
p

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
# np.dot
q = np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])

r = np.array([[10,20,30],
              [100,200,300],])
s = np.dot(q,r)
s

array([[ 210,  420,  630],
       [ 430,  860, 1290],
       [ 650, 1300, 1950],
       [ 870, 1740, 2610]])

In [28]:
# @
q@r

array([[ 210,  420,  630],
       [ 430,  860, 1290],
       [ 650, 1300, 1950],
       [ 870, 1740, 2610]])

In [29]:
t = np.array([1,2,3,4,5])
u = np.array([12,13,14,15,16])
print(t@u)
print(np.dot(t,u))

220
220


In [30]:
# mean, median, min, max, sum, std
print(np.min(s))
print(np.max(s))
print(np.mean(s))
print(np.median(s))
print(np.sum(s))
print(np.std(s))

210
2610
1080.0
865.0
12960
690.4587846738814


In [31]:
# slicing
v = np.array([1,2,3,4,5,6,7,8,9])
v[1: 5]

array([2, 3, 4, 5])

In [32]:
v[4: ]

array([5, 6, 7, 8, 9])

In [33]:
v[-5: -2]

array([5, 6, 7])

In [34]:
w = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])
w

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
print(w>8)

[[False False False False False]
 [False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [36]:
w[2,1]

12

In [37]:
w[:2, 2:4]

array([[3, 4],
       [8, 9]])

In [38]:
# Transpose
w.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [39]:
print(f"shape of w is : {w.shape}")
print(f"shape of transpose of w is : {w.T.shape}")

shape of w is : (4, 5)
shape of transpose of w is : (5, 4)


In [40]:
# cumsum
a1 = np.array([[1,2,3],[4,5,6]])
np.cumsum(a1)

array([ 1,  3,  6, 10, 15, 21])

In [41]:
# cumsum
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[10,20,30],[40,50,60]])

np.cumsum(a1+a2)

array([ 11,  33,  66, 110, 165, 231])

In [42]:
# cumsum
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[10,20,30],[40,50,60]])

np.cumsum(a1+a2, axis=0)

array([[11, 22, 33],
       [55, 77, 99]])

In [43]:
y1 = np.array([10,12,13,14,15,16,17])
y2 = np.array([16,17,18,19,20])
y = np.intersect1d(y1, y2)
y

array([16, 17])

In [44]:
z = np.array([['a','b','c'],
              ['d','e','f']])
z

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [45]:
# unique
np.unique(z)

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [46]:
# np.random.seed
np.random.seed(10)
s=np.random.random(5)                   # If you change the seed value, you will get a different set of random numbers.
print("The random numbers are:")
print(s)

The random numbers are:
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]


In [47]:
# Armin Amani